version: "3.8"

services:
  dev-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test_db
    ports:
      - "3300:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  adminer:
    image: adminer:latest
    ports:
      - "3002:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=dev-db
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis
    ports:
      - 3003:8081
